services:
  postgres:
    image: postgres:15
    container_name: b2b-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: b2b_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: b2b-redis
    restart: always
    ports:
      - "6379:6379"

  stripe:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --forward-to http://host.docker.internal:3000/webhook
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    ports:
      - "12111:12111"

volumes:
  postgres_data:
